import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NavBar } from '@app/components/NavBar';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

import localFont from 'next/font/local';

import { Footer } from '@app/sections/Footer';

export const recklessNeue = localFont({
  src: [
    {
      path: '../../public/fonts/RecklessNeue-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-Book.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-BookItalic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/RecklessNeue-Heavy.ttf',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-HeavyItalic.ttf',
      weight: '900',
      style: 'italic',
    },
    {
      path: '../../public/fonts/RecklessNeue-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-LightItalic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../../public/fonts/RecklessNeue-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-MediumItalic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../../public/fonts/RecklessNeue-Regular.ttf',
      weight: 'normal',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-RegularItalic.ttf',
      weight: 'normal',
      style: 'italic',
    },
    {
      path: '../../public/fonts/RecklessNeue-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-SemiBoldItalic.ttf',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../../public/fonts/RecklessNeue-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RecklessNeue-ThinItalic.ttf',
      weight: '100',
      style: 'italic',
    },
  ],
  variable: '--font-reckless-neue',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${recklessNeue.variable}`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
